<#
Google Code Jam 2015 (4/11/2015) 
A. Standing Ovation entry code file

Variables: 
$codejaminput = File input 
$testmax = Max number of test cases, top line of input file.
$testcase = Current test case number, generated by foreach.
$audiencesize = sum of #S0..#Smax, need to sum
$Smaxinput = $codejaminput[%n]-$audiencesize
$numofSmax= select-string $Smaxinput -first 1, seeds needed for solution

$absof =IF($numofSmax>0,$numofSmax,0), positive value of seeds
$codejamoutput = "Case #" & $testcase & ": " & 

#>


$codejaminput = Get-Content C:\users\sgillie\desktop\input.txt

$testmax = $codejaminput[0] 


foreach ($testcase in $testmax) {
$testline = $codejaminput[ $testcase + 1 ] 
# 1. pull in line and parse
$Smax = $testline.split(" ")[ 0 ]
$audience = ($testline.split(" ")[1]).ToCharArray()
<#

#>
$sumaudience = 

# 2. maths
$audiencesize = "=SUM(H4:L4)"
$Smaxinput = $codejaminput[%n]-$audiencesize
$numofSmax = select-string $smaxinput -first 1
$absof =IF($numofSmax>0,$numofSmax,0)

$codejamoutput[$testcase] = "Case #" & $testcase & ": " & $absof
# 3. output to output array
}

$codejamoutput | Out-File C:\users\sgillie\desktop\output.txt
